### ISSUE TITLE
Ulm University of Applied Sciences is using jniosemu

### ISSUE THREAD

**Issue by joblo2213** [stpe/jniosemu#6]
Hey there! 

I'm a student at [THU (Ulm University of Applied Science)](https://studium.hs-ulm.de/en) and I just wanted to inform you  that we will be using jniosemo in our microcomputer technology laboratory exercises.

Thanks for your work, have a great day!

**Comment by stpe** [comment]
Great to hear @joblo2213 - thanks for posting! Great to see it is still useful even after close to 15 years since it was made (as a university course project). 🥳Ping @WizKid
